CREATE TABLE IF NOT EXISTS BLOGS (
	ID UUID PRIMARY KEY,
	USER_ID UUID NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
	-- CONTENT
	SLUG TEXT UNIQUE NOT NULL,
	IMAGE_URL TEXT,
	TITLE TEXT NOT NULL,
	EXCERPT TEXT,
	CONTENT TEXT NOT NULL,
	PUBLISHED BOOLEAN NOT NULL DEFAULT FALSE,
	PUBLISHED_AT TIMESTAMPTZ,
	-- META
	CREATED TIMESTAMPTZ,
	UPDATED TIMESTAMPTZ
);