CREATE TABLE IF NOT EXISTS SESSIONS (
	ID UUID PRIMARY KEY,
	USER_ID UUID NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
	-- DEVICE
	IP TEXT,
	BROWSER TEXT,
	CPU TEXT,
	DEVICE TEXT,
	ENGINE TEXT,
	OS TEXT,
	-- META
	CREATED TIMESTAMPTZ,
    UPDATED TIMESTAMPTZ,
	EXPIRED TIMESTAMPTZ
);