CREATE TABLE IF NOT EXISTS USERS (
	ID UUID PRIMARY KEY,
	-- AUTHENTICATION & AUTHORIZATION
	EMAIL TEXT UNIQUE NOT NULL,
	HASH TEXT NOT NULL,
	ROLE TEXT NOT NULL,
	-- PASSWORD RESET
	PASSWORD_RESET_OTP TEXT,
	PASSWORD_RESET_EXPIRY TIMESTAMPTZ,
	PASSWORD_RESET_ATTEMPTS INT NOT NULL,
	-- PROFILE
	FIRST_NAME TEXT NOT NULL,
	LAST_NAME TEXT NOT NULL,
	YEAR_OF_BIRTH INT NOT NULL,
	SEX TEXT NOT NULL,
	COUNTRY TEXT NOT NULL,
	-- META
	DISABLED BOOLEAN,
	VERIFIED BOOLEAN,
	CREATED TIMESTAMPTZ,
	UPDATED TIMESTAMPTZ
);